import { useState } from "react";

const allMedicines = [
 
  { name: "Arnica Montana", price: "₹120" },
  { name: "Belladonna", price: "₹95" },
  { name: "Nux Vomica", price: "₹110" },
  { name: "Rhus Toxicodendron", price: "₹130" },
  { name: "Bryonia Alba", price: "₹100" },
  { name: "Pulsatilla", price: "₹115" },
  { name: "Aconitum Napellus", price: "₹105" },
  { name: "Calcarea Carbonica", price: "₹125" },
  { name: "Colocynthis", price: "₹90" },
  { name: "Gelsemium", price: "₹115" },
  { name: "Lycopodium", price: "₹120" },
  { name: "Hypericum Perforatum", price: "₹130" },
  { name: "Ferrum Phosphoricum", price: "₹100" },
  { name: "Carbo Vegetabilis", price: "₹110" },
  { name: "Magnesia Phosphorica", price: "₹95" },
  { name: "Sulphur", price: "₹115" },
  { name: "Chamomilla", price: "₹90" },
  { name: "Antimonium Crudum", price: "₹120" },
  { name: "Mercurius Solubilis", price: "₹105" },
  { name: "Sepia", price: "₹125" },
  { name: "Silicea", price: "₹110" },
  { name: "Apis Mellifica", price: "₹95" },
  { name: "Calcarea Fluorica", price: "₹130" },
  { name: "Phosphorus", price: "₹115" },
  { name: "Lachesis", price: "₹120" },
  { name: "Nux Moschata", price: "₹110" },
  { name: "Cocculus Indicus", price: "₹90" },
  { name: "Calcarea Sulphurica", price: "₹100" },
  { name: "Bryonia Alba", price: "₹100" },
  { name: "Pulsatilla", price: "₹115" },
  { name: "Aconitum Napellus", price: "₹105" },
  { name: "Calcarea Carbonica", price: "₹125" },
  { name: "Colocynthis", price: "₹90" },
  { name: "Gelsemium", price: "₹115" },


  { name: "Lycopodium", price: "₹120" },
  { name: "Hypericum Perforatum", price: "₹130" },
  { name: "Ferrum Phosphoricum", price: "₹100" },
  { name: "Carbo Vegetabilis", price: "₹110" },
  { name: "Magnesia Phosphorica", price: "₹95" },
  { name: "Sulphur", price: "₹115" },
  { name: "Chamomilla", price: "₹90" },
  { name: "Antimonium Crudum", price: "₹120" },
  { name: "Mercurius Solubilis", price: "₹105" },
  { name: "Sepia", price: "₹125" },
  { name: "Silicea", price: "₹110" },
  { name: "Apis Mellifica", price: "₹95" },
  { name: "Calcarea Fluorica", price: "₹130" },
  { name: "Phosphorus", price: "₹115" },
  { name: "Lachesis", price: "₹120" },
  { name: "Nux Moschata", price: "₹110" },
  { name: "Cocculus Indicus", price: "₹90" },
  { name: "Calcarea Sulphurica", price: "₹100" },
  

  { name: "AALSERUM", price: "₹100" },
  { name: "ABIES CAN", price: "₹100" },
  { name: "ABIES NIG", price: "₹100" },
  { name: "ABROTANUM", price: "₹100" },
  { name: "ABSINTHIUM", price: "₹100" },
  { name: "ACALYPHA INDICA", price: "₹100" },
  { name: "ACID ACETICUM", price: "₹100" },
  { name: "ACID BENZ", price: "₹100" },
  { name: "ACID CARBOLIC", price: "₹100" },
  { name: "ACID CHRYSOPHAR", price: "₹100" },
  { name: "ACID FLUOR", price: "₹100" },
  { name: "ACID FORMICICUM", price: "₹100" },
  { name: "ACID HYDROCYANIC", price: "₹100" },
  { name: "ACID LACTICUM", price: "₹100" },
  { name: "ACID MURIATICUM", price: "₹100" },
  { name: "ACID NITRICUM", price: "₹100" },
  { name: "ACID OXALICUM", price: "₹100" },
  { name: "ACID PHOSPHORIC", price: "₹100" },
  { name: "ACID PIC", price: "₹100" },
  { name: "ACID SALICYLICU", price: "₹100" },
  { name: "ACID SULPH.", price: "₹100" },
  { name: "ACID URICUM", price: "₹100" },
  { name: "ACONITE NAP", price: "₹100" },
  { name: "ACTAEA SPICATA", price: "₹100" },
  { name: "ADRENALINUM", price: "₹100" },
  { name: "AESCULUS HIP.", price: "₹100" },
  { name: "AETHUSA CYNAP.", price: "₹100" },
  { name: "AGARICUS MUS.", price: "₹100" },
  { name: "AGNUS CAST", price: "₹100" },
  { name: "AGRAPHIS NUT", price: "₹100" },
  { name: "ALLIUM CEPA", price: "₹100" },
  { name: "ALLIUM SAT.", price: "₹100" },
  { name: "ALOE SOC", price: "₹100" },
  { name: "ALSTONIA CONS", price: "₹100" },
  { name: "ALUMEN", price: "₹100" },
  { name: "ALUMINA", price: "₹100" },
  { name: "AMBRA G.", price: "₹100" },
  { name: "AMMONIUM CARB", price: "₹100" },
  { name: "AMMONIUM MUR", price: "₹100" },
  { name: "AMMONIUM PHOS", price: "₹100" },
  { name: "AMYLIUM NIT", price: "₹100" },
  { name: "ANACARDIUM OCC.", price: "₹100" },
  { name: "ANACARDIUM ORI.", price: "₹100" },
  { name: "ANAGALLIS ARV.", price: "₹100" },
  { name: "ANGUSTURA V.", price: "₹100" },
  { name: "ANTHRACINUM", price: "₹100" },
  { name: "ANTIMONIUM ARS.", price: "₹100" },
  { name: "ANTIMONIUM CRUD", price: "₹100" },
  { name: "ANTIMONIUM TART", price: "₹100" },
  { name: "APIS MELL", price: "₹100" },
  { name: "APOCYNUM CAN", price: "₹100" },
  { name: "ARALIA RAC", price: "₹100" },
  { name: "ARANEA D.", price: "₹100" },
  { name: "ARGENTUM MET", price: "₹100" },
  { name: "ARGENTUM NIT", price: "₹100" },
  { name: "ARGENTUM PROT", price: "₹100" },
  { name: "ARGENTUM VIV", price: "₹100" },
  { name: "ARISTOLOCHIA", price: "₹100" },
  { name: "ARUM TRIPHYLL", price: "₹100" },
  { name: "ARUNDO DONAX", price: "₹100" },
  { name: "ASAFETIDA", price: "₹100" },
  { name: "ASARUM EUROPE", price: "₹100" },
  { name: "ASARUM VIRID", price: "₹100" },


  { name: "ASPIDIUM FILIX", price: "₹100" },
  { name: "ASPIDIUM NIP.", price: "₹100" },
  { name: "ASPIDIUM TRIC.", price: "₹100" },
  { name: "ASPIDIUM VUL.", price: "₹100" },
  { name: "ASTRAGALUS MEM.", price: "₹100" },
  { name: "ASTRAGALUS P.", price: "₹100" },
  { name: "ASTRAGALUS S.", price: "₹100" },
  { name: "ASTRAGALUS SULP.", price: "₹100" },
  { name: "ASTRAGALUS TRIC.", price: "₹100" },
  { name: "ASTRAGALUS VUL.", price: "₹100" },
  { name: "ATROPA BELL", price: "₹100" },
  { name: "AURUM MET", price: "₹100" },
  { name: "AURUM NIT", price: "₹100" },
  { name: "AURUM PROT", price: "₹100" },
  { name: "AURUM VIV", price: "₹100" },
  { name: "AVIARE", price: "₹100" },


  { name: "BACILLIUM", price: "₹100" },
  { name: "BADIAGA", price: "₹100" },
  { name: "BAPTISIA TINC", price: "₹100" },
  { name: "BARYTA CARB", price: "₹100" },
  { name: "BARYTA IOD", price: "₹100" },
  { name: "BARYTA MUR.", price: "₹100" },
  { name: "BARYTA PHOS.", price: "₹100" },
  { name: "BELLADONA", price: "₹100" },
  { name: "BELLIS PER", price: "₹100" },
  { name: "BERBERIS AQUIFO", price: "₹100" },
  { name: "BERBERIS VULG", price: "₹100" },
  { name: "BISMUTHUM MET", price: "₹100" },
  { name: "BLATTA ORI.", price: "₹100" },
  { name: "BORAX", price: "₹100" },
  { name: "BOTHROPS LANC", price: "₹100" },
  { name: "BOVISTA", price: "₹100" },
  { name: "BROMIUM", price: "₹100" },
  { name: "BRYONIA ALB", price: "₹100" },
  { name: "BUFO RANA", price: "₹100" },
  { name: "CACTUS G.", price: "₹100" },
  { name: "CADMIUM SULF", price: "₹100" },
  { name: "CAJUPUTUM", price: "₹100" },
  { name: "CALADIUM SEG.", price: "₹100" },
  { name: "CALC. ARS", price: "₹100" },
  { name: "CALC CARB HAH", price: "₹100" },
  { name: "CALC FLUOR", price: "₹100" },
  { name: "CALC LOD", price: "₹100" },
  { name: "CALC PHOS", price: "₹100" },
  { name: "CALC PIC", price: "₹100" },
  { name: "CALC RENAL", price: "₹100" },
  { name: "CALC SILLICATA", price: "₹100" },
  { name: "CALC SULPH", price: "₹100" },
  { name: "CALENDULA OFF", price: "₹100" },
  { name: "CAMPHORA", price: "₹100" },
  { name: "CANTHARIS", price: "₹100" },
  { name: "CAPSICUM", price: "₹100" },
  { name: "CARBO ANIMAL", price: "₹100" },
  { name: "CARBO SULPH", price: "₹100" },
  { name: "CARBO VEG", price: "₹100" },
  { name: "CARCINOSIN", price: "₹100" },
  { name: "CARDUUS MAR", price: "₹100" },
  { name: "CAULOPHYLLUM", price: "₹100" },
  { name: "CAUSTICUM HAH", price: "₹100" },
  { name: "CEANOTHUS AN", price: "₹100" },
  { name: "CHIMPHILA UMB", price: "₹100" },
  { name: "CHINA OFF", price: "₹100" },
  { name: "CHINIUM ARS.", price: "₹100" },
  { name: "CHINIUM SULPH", price: "₹100" },
  { name: "CHIONANTHUS V", price: "₹100" },
  { name: "CHOLESTERINUM", price: "₹100" },
  { name: "CICUTA V.", price: "₹100" },
  { name: "CIMEX", price: "₹100" },
  { name: "CIMICIFUGA", price: "₹100" },
  { name: "CINA", price: "₹100" },
  { name: "CINNABARIS", price: "₹100" },
  { name: "CISTUS CAN", price: "₹100" },
  { name: "CLEMATIS", price: "₹100" },
  { name: "COCCUIND IND", price: "₹100" },
  { name: "COCCUS CACTI", price: "₹100" },
  { name: "COFEA CRUD", price: "₹100" },
  { name: "COLCHICUM", price: "₹100" },
  { name: "COLLINSONIA CAN", price: "₹100" },
  { name: "COLOCYNTHIS", price: "₹100" },
  { name: "CONDURANGO", price: "₹100" },
  { name: "CONIUM MAC.", price: "₹100" },
  { name: "COPAIVA", price: "₹100" },
  { name: "CROCUS SAT", price: "₹100" },
  { name: "CROTALUS HOR", price: "₹100" },
  { name: "CROTON TIG", price: "₹100" },
  { name: "CUPRUM ACET.", price: "₹100" },
  { name: "CUPRUM ARS.", price: "₹100" },
  { name: "CUPRUM MET.", price: "₹100" },
  { name: "CURARE", price: "₹100" },
  { name: "CYCLAMEN", price: "₹100" },


  { name: "DIGITALIS PUR", price: "₹100" },
  { name: "DIOSCOREA VILL", price: "₹100" },
  { name: "DIPHTHERINUM", price: "₹100" },
  { name: "DOLICHOS PRU", price: "₹100" },
  { name: "DROSERA", price: "₹100" },
  { name: "DULCAMARA", price: "₹100" },
  { name: "ECHINACEA ANG", price: "₹100" },
  { name: "ELAPS COR.", price: "₹100" },
  { name: "EPIGEA R.", price: "₹100" },
  { name: "EQUISETUM H.", price: "₹100" },
  { name: "ERIGERON CAN", price: "₹100" },
  { name: "EUPATORIUM PERF", price: "₹100" },
  { name: "EUPATORIUM PURP", price: "₹100" },
  { name: "EUPHORBIUM", price: "₹100" },
  { name: "EUPHRASIA", price: "₹100" },
  { name: "FAGOPYRUM ESC", price: "₹100" },
  { name: "FERRUM ARS.", price: "₹100" },
  { name: "FERRUM LOD.", price: "₹100" },
  { name: "FERRUM MET.", price: "₹100" },
  { name: "FERRUM PHOS", price: "₹100" },
  { name: "FERRUM PIC.", price: "₹100" },
  { name: "FILIX MAS.", price: "₹100" },
  { name: "FORMICA RUFA", price: "₹100" },
  { name: "FUCUS VES.", price: "₹100" },
  { name: "GAMBOGIA", price: "₹100" },
  { name: "GELSEMIUM", price: "₹100" },
  { name: "GLONOINUM", price: "₹100" },
  { name: "GLYCERINUM", price: "₹100" },
  { name: "GNAPHALIUM POL", price: "₹100" },
  { name: "GRAPHITES", price: "₹100" },
  { name: "GRINDELIA ROB", price: "₹100" },
  { name: "GUAIACUM", price: "₹100" },
  { name: "GUN POWDER", price: "₹100" },
  { name: "HAMAMELIS VIRG", price: "₹100" },
  { name: "HEKLA LAVA", price: "₹100" },
  { name: "HELLEBORUS", price: "₹100" },
  { name: "HELONIAS D", price: "₹100" },
  { name: "HEPAR SULPH", price: "₹100" },
  { name: "HYDRASTIS CAN", price: "₹100" },
  { name: "HYDROCOTYLE AS", price: "₹100" },
  { name: "HYDROPHOBINUM", price: "₹100" },
  { name: "HYOSCYAMUS NIG", price: "₹100" },
  { name: "HYPERICUM PERF", price: "₹100" },
  { name: "IBERIS AMA", price: "₹100" },
  { name: "IGNATIA AMAR", price: "₹100" },
  { name: "INFLUENZINUM", price: "₹100" },
  { name: "INSULIN", price: "₹100" },
  { name: "IODUM", price: "₹100" },
  { name: "IPECACUANHA", price: "₹100" },
  { name: "IRIS TENAX", price: "₹100" },
  { name: "IRIS VER", price: "₹100" },
  { name: "JABORANDI", price: "₹100" },
  { name: "JALAPA", price: "₹100" },
  { name: "JATROPHA C.", price: "₹100" },
  { name: "JUSTICIA AD", price: "₹100" },


  { name: "KALI ARS.", price: "₹100" },
  { name: "KALI BICH", price: "₹100" },
  { name: "KALI BROM", price: "₹100" },
  { name: "KALI CARB", price: "₹100" },
  { name: "KALI LOD", price: "₹100" },
  { name: "KALI MUR", price: "₹100" },
  { name: "KALI NIT", price: "₹100" },
  { name: "KALI PHOS", price: "₹100" },
  { name: "KALI SULPH", price: "₹100" },
  { name: "KALMIA LAT.", price: "₹100" },
  { name: "KREOSOTUM", price: "₹100" },
  { name: "LAC CAN", price: "₹100" },
  { name: "LAC. DEF.", price: "₹100" },
  { name: "LAC. VAC. DEF.", price: "₹100" },
  { name: "LACHNANTHES T", price: "₹100" },
  { name: "LAPIS ALB", price: "₹100" },
  { name: "LATHYRUS SAT.", price: "₹100" },
  { name: "LATRODECTUS M", price: "₹100" },
  { name: "LAUROCERASUS", price: "₹100" },
  { name: "LEDUM PAL", price: "₹100" },
  { name: "LEMNA MINOR", price: "₹100" },
  { name: "LEPTANDRA", price: "₹100" },
  { name: "LILLIUM TIG.", price: "₹100" },
  { name: "LITHIUM CARB", price: "₹100" },
  { name: "LOBELIA INF", price: "₹100" },
  { name: "LYCOPODIUM", price: "₹100" },
  { name: "LYCOPUS V.", price: "₹100" },
  { name: "MACROTINUM", price: "₹100" },
  { name: "MAGN. CARB", price: "₹100" },
  { name: "MAGN. MUR", price: "₹100" },
  { name: "MAGN. PHOS", price: "₹100" },
  { name: "MALANDRINUM", price: "₹100" },
  { name: "MANGANUM ACET.", price: "₹100" },
  { name: "MANGANUM MET", price: "₹100" },
  { name: "MEDORRHINUM", price: "₹100" },
  { name: "MELILOTUS OFF", price: "₹100" },
  { name: "MENTHA PIP", price: "₹100" },
  { name: "MEPHITIS PUT", price: "₹100" },
  { name: "MERC COR", price: "₹100" },
  { name: "MERC CYAN", price: "₹100" },
  { name: "MERC DUL", price: "₹100" },
  { name: "MERC IOD FLAV", price: "₹100" },
  { name: "MERC IOD RUB", price: "₹100" },
  { name: "MERC SOL", price: "₹100" },
  { name: "MERC VIV", price: "₹100" },
  { name: "MEZEREUM", price: "₹100" },
  { name: "MILLEFOLIUM", price: "₹100" },
  { name: "MORBILLINUM", price: "₹100" },
  { name: "MOSCHUS", price: "₹100" },
  { name: "MUREX PURP", price: "₹100" },
  { name: "MYRISTICA SEB", price: "₹100" },
  { name: "NAJA T.", price: "₹100" },
  { name: "NAPHTHALINUM", price: "₹100" },
  { name: "NATRUM ARS.", price: "₹100" },
  { name: "NATRUM CARB", price: "₹100" },
  { name: "NATRUM MUR", price: "₹100" },
  { name: "NATRUM PHOS", price: "₹100" },
  { name: "NATRUM SALICY", price: "₹100" },
  { name: "NATRUM SULPH", price: "₹100" },
  { name: "NUX MOSCH", price: "₹100" },
  { name: "NUX VOMICA", price: "₹100" },
  { name: "OCIMUM CAN", price: "₹100" },
  { name: "OENANTHE CROC", price: "₹100" },
  { name: "OLEANDER", price: "₹100" },
  { name: "OLEUM JEC", price: "₹100" },
  { name: "ONOSMODIUM V", price: "₹100" },
  { name: "OPIUM", price: "₹100" },
  { name: "ORNITHOGALUM U", price: "₹100" },
  { name: "OSMIUM", price: "₹100" },
  { name: "OVA TESTA", price: "₹100" },
  { name: "PEAONIA OFF", price: "₹100" },
  { name: "PAROTIDINUM", price: "₹100" },
  { name: "PERTUSSIN", price: "₹100" },
  { name: "PETROLEUM", price: "₹100" },
  { name: "PETROSELINUM", price: "₹100" },
  { name: "PHOSPHORUS", price: "₹100" },
  { name: "PHYSOSTIGMA VEN", price: "₹100" },
  { name: "PHYTOLACCA BERRY", price: "₹100" },
  { name: "PHYTOLACCA DEC", price: "₹100" },
  { name: "PICHI", price: "₹100" },
  { name: "PIX. LIQ.", price: "₹100" },
  { name: "PLANTAGO M.", price: "₹100" },
  { name: "PLATINUM MET", price: "₹100" },
  { name: "PLUMBUM MET", price: "₹100" },
  { name: "PODOPHYLLUM PEL", price: "₹100" },
  { name: "POTHOS FOET.", price: "₹100" },
  { name: "PSORINUM", price: "₹100" },
  { name: "PULSATILLA", price: "₹100" },
  { name: "PYROGENIUM", price: "₹100" },
  { name: "RADIUM BROM", price: "₹100" },
  { name: "RANUNCULUS B", price: "₹100" },
  { name: "RAPHANUS SAT.", price: "₹100" },
  { name: "RATANHIA", price: "₹100" },
  { name: "RHEUM", price: "₹100" },
  { name: "RHODODEMDRON", price: "₹100" },
  { name: "RHUS TOX", price: "₹100" },
  { name: "RHUS VEN", price: "₹100" },
  { name: "RICINUS COM", price: "₹100" },
  { name: "ROBINIA PSEUD", price: "₹100" },
  { name: "ROSMARINUS OFF", price: "₹100" },
  { name: "RUMEX CRIS", price: "₹100" },
  { name: "RUTA G", price: "₹100" },


  { name: "SABADILLA", price: "₹100" },
  { name: "SABAL SERR", price: "₹100" },
  { name: "SABINA", price: "₹100" },
  { name: "SAMBUCUS CAN", price: "₹100" },
  { name: "SAMBUCUS NIG.", price: "₹100" },
  { name: "SANGUINARIA CAN", price: "₹100" },
  { name: "SANGUINARIA NIT", price: "₹100" },
  { name: "SANICULA A.", price: "₹100" },
  { name: "SANTONINUM", price: "₹100" },
  { name: "SARSAPARILLA", price: "₹100" },
  { name: "SCIRRHINUM", price: "₹100" },
  { name: "SECALE COR", price: "₹100" },
  { name: "SELENIUM", price: "₹100" },
  { name: "SENECIA A", price: "₹100" },
  { name: "SENEGA", price: "₹100" },
  { name: "SEPIA", price: "₹100" },
  { name: "SILLOCEA", price: "₹100" },
  { name: "SOLIDAGO V.", price: "₹100" },
  { name: "SPIGELIA", price: "₹100" },
  { name: "SPONGIA T.", price: "₹100" },
  { name: "SQUILA", price: "₹100" },
  { name: "STANNUM MET", price: "₹100" },
  { name: "STAPHYSAGRIA", price: "₹100" },
  { name: "STICTA P.", price: "₹100" },
  { name: "STRAMONIUM", price: "₹100" },
  { name: "STRONTIA CARB", price: "₹100" },
  { name: "STROPHANTHUS", price: "₹100" },
  { name: "STRYCHNINUM", price: "₹100" },
  { name: "SULFUR", price: "₹100" },
  { name: "SULFUR LOD.", price: "₹100" },
  { name: "SYMPHYTUM", price: "₹100" },
  { name: "SYPHILINUM", price: "₹100" },
  { name: "TABACUM", price: "₹100" },
  { name: "TERAXACUM", price: "₹100" },
  { name: "TARENTULA C.", price: "₹100" },
  { name: "TERENTULA H.", price: "₹100" },
  { name: "TELLURIUM", price: "₹100" },
  { name: "TERABINTHINA", price: "₹100" },
  { name: "TEUCRIUM M.V.", price: "₹100" },
  { name: "THALLIUM MET", price: "₹100" },
  { name: "THERIDION C", price: "₹100" },
  { name: "THIOSINAMINUM", price: "₹100" },
  { name: "THUJA OCCID", price: "₹100" },
  { name: "THYMOLUM", price: "₹100" },
  { name: "THYROIDINUM", price: "₹100" },
  { name: "TITANIUM MET", price: "₹100" },
  { name: "TRILLIUM PEND", price: "₹100" },
  { name: "TROMBIDIUM", price: "₹100" },
  { name: "TUBERCULINUM BOV", price: "₹100" },
  { name: "TUBERCULINUM K.", price: "₹100" },
  { name: "TYPHODINUM", price: "₹100" },
  { name: "URANIUM NIT", price: "₹100" },
  { name: "UREA", price: "₹100" },
  { name: "URTICA UR.", price: "₹100" },
  { name: "USTILAGO", price: "₹100" },
  { name: "VACCININUM", price: "₹100" },
  { name: "VALERIANA OFF", price: "₹100" },
  { name: "VANADIUM", price: "₹100" },
  { name: "VARIOLINUM", price: "₹100" },
  { name: "VERATRUM ALB", price: "₹100" },
  { name: "VERATRUM VIR", price: "₹100" },
  { name: "VERBASCUM THA", price: "₹100" },
  { name: "VIBURNUM OP", price: "₹100" },
  { name: "VINCA MINOR", price: "₹100" },
  { name: "VIOLA ODOR", price: "₹100" },
  { name: "VIOLA TRI", price: "₹100" },
  { name: "VIPERA", price: "₹100" },
  { name: "VISCUM ALB", price: "₹100" },
  { name: "WISABADON", price: "₹100" },
  { name: "WYETHIA", price: "₹100" },
  { name: "X-RAY", price: "₹100" },
  { name: "ZINCUM MET", price: "₹100" },
  { name: "ZINCUM PHOS", price: "₹100" },
  { name: "ZINCUM PIC", price: "₹100" },
  { name: "ZINCUM SULF", price: "₹100" },
  { name: "ZINGIBER", price: "₹100" },

  { name: "CALC. FLOUR", price: "₹100" },
  { name: "CALC. PHOS", price: "₹100" },
  { name: "CALC. SULF", price: "₹100" },
  { name: "FERR. PHOS", price: "₹100" },
  { name: "KALI MUR", price: "₹100" },
  { name: "KALI PHOS", price: "₹100" },
  { name: "KALI SULF", price: "₹100" },
  { name: "MAGN. PHOS", price: "₹100" },
  { name: "NATR. SULF", price: "₹100" },
  { name: "SILICEA", price: "₹100" },
  { name: "FIVE PHOS", price: "₹100" },


  { name: "BC 1", price: "₹100" },
  { name: "BC 2", price: "₹100" },
  { name: "BC 3", price: "₹100" },
  { name: "BC 4", price: "₹100" },
  { name: "BC 5", price: "₹100" },
  { name: "BC 6", price: "₹100" },
  { name: "BC 7", price: "₹100" },
  { name: "BC 8", price: "₹100" },
  { name: "BC 9", price: "₹100" },
  { name: "BC 10", price: "₹100" },
  { name: "BC 11", price: "₹100" },
  { name: "BC 12", price: "₹100" },
  { name: "BC 13", price: "₹100" },
  { name: "BC 14", price: "₹100" },
  { name: "BC 15", price: "₹100" },
  { name: "BC 16", price: "₹100" },
  { name: "BC 17", price: "₹100" },
  { name: "BC 18", price: "₹100" },
  { name: "BC 19", price: "₹100" },
  { name: "BC 20", price: "₹100" },
  { name: "BC 21", price: "₹100" },
  { name: "BC 22", price: "₹100" },
  { name: "BC 23", price: "₹100" },
  { name: "BC 24", price: "₹100" },
  { name: "BC 25", price: "₹100" },
  { name: "BC 26", price: "₹100" },
  { name: "BC 27", price: "₹100" },
  { name: "BC 28", price: "₹100" },


  { name: "R 1", price: "₹100" },
  { name: "R 2", price: "₹100" },
  { name: "R 3", price: "₹100" },
  { name: "R 4", price: "₹100" },
  { name: "R 5", price: "₹100" },
  { name: "R 6", price: "₹100" },
  { name: "R 7", price: "₹100" },
  { name: "R 8", price: "₹100" },
  { name: "R 9", price: "₹100" },
  { name: "R 10", price: "₹100" },
  { name: "R 11", price: "₹100" },
  { name: "R 12", price: "₹100" },
  { name: "R 13", price: "₹100" },
  { name: "R 14", price: "₹100" },
  { name: "R 15", price: "₹100" },
  { name: "R 16", price: "₹100" },
  { name: "R 17", price: "₹100" },
  { name: "R 18", price: "₹100" },
  { name: "R 19", price: "₹100" },
  { name: "R 20", price: "₹100" },
  { name: "R 21", price: "₹100" },
  { name: "R 22", price: "₹100" },
  { name: "R 23", price: "₹100" },
  { name: "R 24", price: "₹100" },
  { name: "R 25", price: "₹100" },
  { name: "R 26", price: "₹100" },
  { name: "R 27", price: "₹100" },
  { name: "R 28", price: "₹100" },
  { name: "R 29", price: "₹100" },
  { name: "R 30", price: "₹100" },
  { name: "R 31", price: "₹100" },
  { name: "R 32", price: "₹100" },
  { name: "R 33", price: "₹100" },
  { name: "R 34", price: "₹100" },
  { name: "R 35", price: "₹100" },
  { name: "R 36", price: "₹100" },
  { name: "R 37", price: "₹100" },
  { name: "R 38", price: "₹100" },
  { name: "R 39", price: "₹100" },
  { name: "R 40", price: "₹100" },
  { name: "R 41", price: "₹100" },
  { name: "R 42", price: "₹100" },
  { name: "R 43", price: "₹100" },
  { name: "R 44", price: "₹100" },
  { name: "R 45", price: "₹100" },
  { name: "R 46", price: "₹100" },
  { name: "R 47", price: "₹100" },
  { name: "R 48", price: "₹100" },
  { name: "R 49", price: "₹100" },
  { name: "R 50", price: "₹100" },
  { name: "R 51", price: "₹100" },
  { name: "R 52", price: "₹100" },
  { name: "R 53", price: "₹100" },
  { name: "R 54", price: "₹100" },
  { name: "R 55", price: "₹100" },
  { name: "R 56", price: "₹100" },
  { name: "R 57", price: "₹100" },
  { name: "R 58", price: "₹100" },
  { name: "R 59", price: "₹100" },
  { name: "R 60", price: "₹100" },
  { name: "R 61", price: "₹100" },
  { name: "R 62", price: "₹100" },
  { name: "R 63", price: "₹100" },
  { name: "R 64", price: "₹100" },
  { name: "R 65", price: "₹100" },
  { name: "R 66", price: "₹100" },
  { name: "R 67", price: "₹100" },
  { name: "R 68", price: "₹100" },
  { name: "R 69", price: "₹100" },
  { name: "R 70", price: "₹100" },
  { name: "R 71", price: "₹100" },
  { name: "R 72", price: "₹100" },
  { name: "R 73", price: "₹100" },
  { name: "R 74", price: "₹100" },
  { name: "R 75", price: "₹100" },
  { name: "R 76", price: "₹100" },
  { name: "R 77", price: "₹100" },
  { name: "R 78", price: "₹100" },
  { name: "R 79", price: "₹100" },
  { name: "R 80", price: "₹100" },
  { name: "R 81", price: "₹100" },
  { name: "R 82", price: "₹100" },
  { name: "R 83", price: "₹100" },
  { name: "R 84", price: "₹100" },
  { name: "R 85", price: "₹100" },
  { name: "R 86", price: "₹100" },
  { name: "R 87", price: "₹100" },
  { name: "R 88", price: "₹100" },
  { name: "R 89", price: "₹100" },
];


function Medicines({ addToCart }) {
  const [search, setSearch] = useState("");
  const [category, setCategory] = useState("All");

  const filteredMedicines = allMedicines.filter((med) => {
    const matchName = med.name.toLowerCase().includes(search.toLowerCase());
    const matchCategory = category === "All" || med.category === category;
    return matchName && matchCategory;
  });

  return (
    <div style={{ padding: "20px" }}>
      <h1 style={{ textAlign: "center" }}>💊 Our Homeopathy Medicines</h1>

      {/* Search & Filter */}
      <div style={{ display: "flex", justifyContent: "center", gap: "15px", margin: "20px 0" }}>
        <input
          type="text"
          placeholder="Search medicine..."
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          style={{ padding: "8px", width: "200px" }}
        />

        <select value={category} onChange={(e) => setCategory(e.target.value)} style={{ padding: "8px" }}>
          <option>All</option>
          <option>Pain</option>
          <option>Fever</option>
          <option>Digestion</option>
        </select>
      </div>

      {/* Cards */}
      <div style={{
        display: "grid",
        gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
        gap: "20px",
        marginTop: "30px"
      }}>
        {filteredMedicines.map((med, index) => (
          <div key={index} style={{
            border: "1px solid #ddd",
            borderRadius: "12px",
            padding: "15px",
            boxShadow: "0 4px 8px rgba(0,0,0,0.1)",
            background: "#f9fff9"
          }}>
            <h3>{med.name}</h3>
            <p><b>Price:</b> {med.price}</p>

            <button
              onClick={() => {
                addToCart(med);
                alert("Medicine added to cart");
              }}
              style={{
                padding: "8px 12px",
                background: "#2e7d32",
                color: "white",
                border: "none",
                borderRadius: "6px",
                cursor: "pointer"
              }}
            >
              Add to Cart
            </button>
          </div>
        ))}
      </div>
    </div>
  );
}

export default Medicines;
